package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TeamEntry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html SYSTEM \"about:legacy-compat\" PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Team Entry Form</title>\r\n");
      out.write("\r\n");
      out.write("<title>Dervar Sport Event</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/material.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/font/material-icons.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-ui.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.currency.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\" src=\"js/material.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"heading\">\r\n");
      out.write("\t\t<label>Dervan Sport Event</label>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<script  type=\"text/javascript\">\r\n");
      out.write("var memberlist=[];\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar noofmember=0;\r\n");
      out.write("\t \tvar dialog = document.querySelector('#teamnameDialog');\r\n");
      out.write("\t    var showDialogButton = document.querySelector('#show-dialog');\r\n");
      out.write("\t    if (!dialog.showModal) {\r\n");
      out.write("\t      dialogPolyfill.registerDialog(dialog);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    showDialogButton.addEventListener('click', function() {\r\n");
      out.write("\t      dialog.showModal();\r\n");
      out.write("\t    });\r\n");
      out.write("\t    dialog.querySelector('.ok').addEventListener('click', function() {\r\n");
      out.write("\t    \tdocument.querySelector('.inputteamname').innerHTML=document.querySelector('#teamName').value+ \" OF \" +document.querySelector('#schoolName').value;\r\n");
      out.write("\t    \tdialog.close();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t    dialog.querySelector('.close').addEventListener('click', function() {\r\n");
      out.write("\t      dialog.close();\r\n");
      out.write("\t    });\r\n");
      out.write("\t    var isedited=false;\r\n");
      out.write("\t    var iseditedid=0;\r\n");
      out.write("\t    var newMemberdialog = document.querySelector('#newmemeber');\r\n");
      out.write("\t    var newmemberButton = document.querySelector('.addmember');\r\n");
      out.write("\t    if (!newMemberdialog.showModal) {\r\n");
      out.write("\t      dialogPolyfill.registerDialog(newMemberdialog);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    newmemberButton.addEventListener('click', function() {\r\n");
      out.write("\t    \teditorinsert();\r\n");
      out.write("\t    \tnewMemberdialog.showModal();\r\n");
      out.write("\t    });\r\n");
      out.write("\t    newMemberdialog.querySelector('.ok').addEventListener('click', function() {\r\n");
      out.write("\t    \tvar numbers = /^[0-9]+$/;\r\n");
      out.write("\t        if(document.getElementById('day').selectedIndex != '0' && document.getElementById('month').selectedIndex != '0' && document.getElementById('year').selectedIndex != '0' && document.getElementById(\"phoneText\").value.match(numbers) && document.getElementById(\"pincodeText\").value.match(numbers) && document.getElementById(\"emergencyphone\").value.match(numbers))\r\n");
      out.write("\t        {\t        \r\n");
      out.write("\t\t        addMember();\r\n");
      out.write("\t\t    \tnewMemberdialog.close();\t    \t\r\n");
      out.write("\t        \treturn true;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        else\r\n");
      out.write("\t        {\r\n");
      out.write("\t        \r\n");
      out.write("\t         //alert(document.getElementById('day').selectedIndex);\r\n");
      out.write("        \t if(document.getElementById('day').selectedIndex == '0' || document.getElementById('month').selectedIndex == '0' || document.getElementById('year').selectedIndex == '0'){\r\n");
      out.write("        \t\t alert('Please select valid date of birth.');\r\n");
      out.write(" \t        \tdocument.getElementById(\"day\").focus();\r\n");
      out.write("        \t }\r\n");
      out.write("\t        \t \r\n");
      out.write("\t        if(!document.getElementById(\"emergencyphone\").value.match(numbers)){\r\n");
      out.write("\t        \talert('Please input numeric values only in Emergency Phone');\r\n");
      out.write("\t        \tdocument.getElementById(\"emergencyphone\").focus();\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t        if(!document.getElementById(\"phoneText\").value.match(numbers)){\r\n");
      out.write("\t        \talert('Please input numeric values only in Phone.');\r\n");
      out.write("\t        \tdocument.getElementById(\"phoneText\").focus();\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\r\n");
      out.write("       \t \tif(!document.getElementById(\"pincodeText\").value.match(numbers)){\r\n");
      out.write("\t        \talert('Please input numeric values only in Pincode');\r\n");
      out.write("\t        \tdocument.getElementById(\"pincodeText\").focus();\r\n");
      out.write("\t        }\r\n");
      out.write("       \t \r\n");
      out.write("\t        return false;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t    \t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t    newMemberdialog.querySelector('.close').addEventListener('click', function() {\r\n");
      out.write("\r\n");
      out.write("\t    \tnewMemberdialog.close();\r\n");
      out.write("\t    });\r\n");
      out.write("\t    editorinsert=function(obj){\r\n");
      out.write("\t    \tvar id;\r\n");
      out.write("\t    \tif(obj!=undefined){\r\n");
      out.write("\t    \t\tid=obj['id'];\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t$('#fistnameText').val((obj!=undefined)?obj[\"fistnameText\"]:'');\r\n");
      out.write("\t    \t$('#middlenameText').val((obj!=undefined)?obj[\"middlenameText\"]:'');\r\n");
      out.write("\t    \t$('#lastnameText').val((obj!=undefined)?obj[\"lastnameText\"]:''); \r\n");
      out.write("\t    \t//$('#day').val((obj!=undefined)?obj[\"day\"]:'');\r\n");
      out.write("\t    \t//$('#month').val((obj!=undefined)?obj[\"month\"]:'');\r\n");
      out.write("\t    \t//$('#year').val((obj!=undefined)?obj[\"year\"]:'');\r\n");
      out.write("\t    \t$('#ageText').text((obj!=undefined)?obj[\"ageText\"]:'');\r\n");
      out.write("\t    \t$('#genderParti').val((obj!=undefined)?obj[\"genderParti\"]:'') ;\r\n");
      out.write("\t    \t$('#addressText').val((obj!=undefined)?obj[\"addressText\"]:'');\r\n");
      out.write("\t    \t$('#stateText').val((obj!=undefined)?obj[\"stateText\"]:'');\r\n");
      out.write("\t    \t$('#cityText').val((obj!=undefined)?obj[\"cityText\"]:'');\r\n");
      out.write("\t    \t$('#pincodeText').val((obj!=undefined)?obj[\"pincodeText\"]:'') \r\n");
      out.write("\t    \t$('#phoneText').val((obj!=undefined)?obj[\"phoneText\"]:'');\r\n");
      out.write("\t    \t$('#emergencyphone').val((obj!=undefined)?obj[\"emergencyphone\"]:'');\r\n");
      out.write("\t    \t$('#emailText').val((obj!=undefined)?obj[\"emailText\"]:'');\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    addMember=function(){\r\n");
      out.write("\t    \tnoofmember=noofmember+1\r\n");
      out.write("\t    \tvar arr={};\r\n");
      out.write("\t    \tif(isedited){\r\n");
      out.write("\t    \t\t$.each(memberlist,function(e,i){\r\n");
      out.write("\t    \t\t\tif(memberlist[e]['id']==iseditedid){\r\n");
      out.write("\t    \t\t\t\tarr=i;\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t}else{\r\n");
      out.write("\t    \t\tarr[\"id\"]=noofmember;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \tarr[\"fistnameText\"]=$('#fistnameText').val();\r\n");
      out.write("\t    \tarr[\"middlenameText\"]=$('#middlenameText').val();\r\n");
      out.write("\t    \tarr[\"lastnameText\"]=$('#lastnameText').val(); \r\n");
      out.write("\t    \tarr[\"day\"]=$('#day').val();\r\n");
      out.write("\t    \tarr[\"month\"]=$('#month').val();\r\n");
      out.write("\t    \tarr[\"year\"]=$('#year').val();\r\n");
      out.write("\t    \tarr[\"ageText\"]=$('#ageText').text();\r\n");
      out.write("\t    \tarr[\"genderParti\"]=$('#genderParti').val() ;\r\n");
      out.write("\t    \tarr[\"addressText\"]=$('#addressText').val();\r\n");
      out.write("\t    \tarr[\"stateText\"]=$('#stateText').val();\r\n");
      out.write("\t    \tarr[\"cityText\"]=$('#cityText').val();\r\n");
      out.write("\t    \tarr[\"pincodeText\"]=$('#pincodeText').val() \r\n");
      out.write("\t    \tarr[\"phoneText\"]=$('#phoneText').val();\r\n");
      out.write("\t    \tarr[\"emergencyphone\"]=$('#emergencyphone').val();\r\n");
      out.write("\t    \tarr[\"emailText\"]=$('#emailText').val();\r\n");
      out.write("\t    \tif(isedited){\r\n");
      out.write("\t    \t\t$('.tablerow[memberrow=\"'+iseditedid+'\"]').html('<div class=\"mdl-cell mdl-cell--3-col\"></div><div class=\"mdl-cell mdl-cell--2-col\"><button class=\"mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-js-ripple-effect  mdl-button--accent delete\"><i class=\"material-icons\">delete</i></button><button class=\"mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-js-ripple-effect  mdl-button--accent edit\"><i class=\"material-icons\">edit</i></button></div><div class=\"mdl-cell mdl-cell--3-col\">'+arr[\"fistnameText\"]+' '+arr[\"middlenameText\"]+' '+arr[\"lastnameText\"]+'</div><div class=\"mdl-cell mdl-cell--2-col\">'+arr[\"ageText\"]+'</div><div class=\"mdl-cell mdl-cell--2-col\"></div>')\r\n");
      out.write("\t    \t}else{\r\n");
      out.write("\t    \tmemberlist.push(arr);\r\n");
      out.write("\t    \tvar trHTML='<div class=\"mdl-grid tablerow\" memberrow=\"'+noofmember+'\"><div class=\"mdl-cell mdl-cell--3-col\"></div><div class=\"mdl-cell mdl-cell--2-col\"><button class=\"mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-js-ripple-effect  mdl-button--accent delete\"><i class=\"material-icons\">delete</i></button><button class=\"mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-js-ripple-effect  mdl-button--accent edit\"><i class=\"material-icons\">edit</i></button></div><div class=\"mdl-cell mdl-cell--3-col\">'+arr[\"fistnameText\"]+' '+arr[\"middlenameText\"]+' '+arr[\"lastnameText\"]+'</div><div class=\"mdl-cell mdl-cell--2-col\">'+arr[\"ageText\"]+'</div><div class=\"mdl-cell mdl-cell--2-col\"></div></div>';\r\n");
      out.write("\t    \t$(\".memberlist\").append(trHTML);\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t$('.edit').off('click').on('click',function(){\r\n");
      out.write("\t    \t\tvar id=$(this).parents('.tablerow').attr('memberrow');\r\n");
      out.write("\t    \t\tiseditedid=id;\r\n");
      out.write("\t    \t\tvar temp;\r\n");
      out.write("\t    \t\t$.each(memberlist,function(e,i){\r\n");
      out.write("\t    \t\t\tif(memberlist[e]['id']==id){\r\n");
      out.write("\t    \t\t\t\ttemp=i;\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t    \t\tisedited=true;\r\n");
      out.write("\t    \t\teditorinsert(temp);\r\n");
      out.write("\t    \t\tnewMemberdialog.showModal();\r\n");
      out.write("\t    \t\treturn false;\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    \t$('.delete').off('click').on('click',function(){\r\n");
      out.write("\t    \t\tvar id=$(this).parents('.tablerow').attr('memberrow');\r\n");
      out.write("\t    \t\tconsole.log(id);\r\n");
      out.write("\t    \t\tvar temp=[];\r\n");
      out.write("\t    \t\t$.each(memberlist,function(e,i){\r\n");
      out.write("\t    \t\t\tif(memberlist[e]['id']!=id){\r\n");
      out.write("\t    \t\t\t\ttemp.push(i);\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t    \t\tmemberlist=temp;\r\n");
      out.write("\t    \t\t$(this).parents('.tablerow').remove();\r\n");
      out.write("\t    \t\treturn false;\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    \tisedited=false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/SportManagmentSystem/TeamEntryServlet\",\r\n");
      out.write("\t\t\tdata:{dataSend:\"category\"},  \r\n");
      out.write("\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\t success:function(data, textStatus, jqXHR)\r\n");
      out.write("\t         {\r\n");
      out.write("\t\t    \tvar e=jQuery.parseJSON(data);\t          \r\n");
      out.write("\t\t    \tconsole.log(\"category\"+e);    \r\n");
      out.write("\t\t        var options = '';\r\n");
      out.write("\t\t        options += '<option value=\"NotSelected\">Select the Game Category</option>';\r\n");
      out.write("\t\t\t\t if(e!=undefined && e!=null && e!=\"\" ){ \r\n");
      out.write("\t\t\t\t\t$.each(e, function(key, value){\r\n");
      out.write("\t\t\t\t\t\toptions += '<option value=\"' + key + '\">' + value + '</option>';\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t        $(\"#category\").html(options);\t        \r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t\t\t\t     \r\n");
      out.write("\t         },\r\n");
      out.write("\t         error:function(xhr,status){\r\n");
      out.write("\t             console.log(status);\r\n");
      out.write("\t      }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#category\").change(function(){\r\n");
      out.write("\t\t if($(this).val()!=\"NotSelected\"){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t       type: \"post\",\r\n");
      out.write("\t\t\t       url:\"/SportManagmentSystem/TeamEntryServlet\",\r\n");
      out.write("\t\t\t       data:\"dataSend=age&&category=\"+$(this).val(),   \r\n");
      out.write("\t\t\t       \r\n");
      out.write("\t\t\t       success:function(data, textStatus, jqXHR)\r\n");
      out.write("\t\t      {\r\n");
      out.write("\t\t\t   \tvar e=jQuery.parseJSON(data);\r\n");
      out.write("\t\t\t    var options = '';\r\n");
      out.write("\t\t     \toptions += '<option value=\"NotSelected\"></option>';\r\n");
      out.write("\t\t\t\tif(e!=undefined && e!=null && e!=\"\" ){\r\n");
      out.write("\t\t\t\t\t$.each(e, function(key, value){\r\n");
      out.write("\t\t\t\t\t\toptions += '<option value=\"' + key + '\">' + value + '</option>';\r\n");
      out.write("\t\t\t\t\t});\t\t     \t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t     $(\"#age\").html(options);\r\n");
      out.write("\t\t },\r\n");
      out.write("\t\t error:function(xhr,status){\r\n");
      out.write("\t\t        console.log(status);\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#captainlist\").change(function(){\r\n");
      out.write("\t\t if($(this).val()!=\"NotSelected\"){\t\t\t \r\n");
      out.write("\t\t\t //alert(\"Text\" + $('#captainlist').text());\r\n");
      out.write("\t    \t    //alert(\"Value\"  + $('#captainlist').val());\t    \t    \r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t       type: \"post\",\r\n");
      out.write("\t\t\t       url:\"/SportManagmentSystem/TeamEntryServlet\",\r\n");
      out.write("\t\t\t       data:\"dataSend=age&&category=\"+$(this).val(),   \t\t\t       \r\n");
      out.write("\t\t\t       success:function(data, textStatus, jqXHR)\r\n");
      out.write("\t\t      {\t\t\t    \t  \r\n");
      out.write("\t\t },\r\n");
      out.write("\t\t error:function(xhr,status){\r\n");
      out.write("\t\t        console.log(status);\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t });\r\n");
      out.write("\t\r\n");
      out.write("\t/*\r\n");
      out.write("\t$(\"#addBtn\").click(function(){\r\n");
      out.write("\t\t    \t   var optionCat ='';\r\n");
      out.write("\t\t    \t   var trHTML = '';\t\r\n");
      out.write("\t\t    \t   $('#tablediv').show();\r\n");
      out.write("\t\t            \ttrHTML += '<tr><td class=\\\"td\\\"id=\\\"fistnameText\\\" >' + $('#fistnameText').val()+'</td>'+ \r\n");
      out.write("\t\t            \t'<td class=\\\"td\\\" id=\\\"lastnameText\\\">' + $('#lastnameText').val() +\r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"middlenameText\\\" >' + $('#middlenameText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"dobText\\\">'+  $('#dobText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"ageText\\\">' + $('#ageText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"genderText\\\" >' + $('#genderText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"addressText\\\" >' + $('#addressText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"stateText\\\">' + $('#stateText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"cityText\\\">' + $('#cityText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"pincodeText\\\">' + $('#pincodeText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"phoneText\\\">' + $('#phoneText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\"  id=\\\"emergencyPhoneText\\\">' + $('#emergencyPhoneText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\" id=\\\"emailText\\\">' + $('#emailText').val() + \r\n");
      out.write("\t\t            \t'</td><td class=\\\"td\\\">'+\"<img src='css/images/edit.png' class='btnEdit'/>\"+\r\n");
      out.write("\t\t            \t\"<img src='css/images/delete.png' class='btnDelete'/>\"+\r\n");
      out.write("\t\t            \t'</td></tr>';\r\n");
      out.write("\t\t            $(\"#partitable\").append(trHTML);\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            $(\".btnEdit\").bind(\"click\",onEdit);\r\n");
      out.write("\t\t        \t$(\".btnDelete\").bind(\"click\",onDelete);\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \tfunction onEdit(){\r\n");
      out.write("\t\t        \t\t\t        \t\t\r\n");
      out.write("\t\t        \t\tvar par = $(this).parent().parent();\r\n");
      out.write("            \t\t\t\r\n");
      out.write("\t            \t\tvar tdfistnameText= par.children(\"td:nth-child(1)\"); \r\n");
      out.write("\t            \t\tvar tdmiddlenameText = par.children(\"td:nth-child(2)\"); \r\n");
      out.write("\t            \t\tvar tdlastnameText = par.children(\"td:nth-child(3)\"); \r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\tvar tddobText = par.children(\"td:nth-child(4)\");\r\n");
      out.write("\t            \t\tvar tdageText = par.children(\"td:nth-child(5)\");\r\n");
      out.write("\t            \t\tvar tdgenderText = par.children(\"td:nth-child(6)\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\tvar tdaddressText = par.children(\"td:nth-child(7)\");\r\n");
      out.write("\t            \t\tvar tdstateText = par.children(\"td:nth-child(8)\");\r\n");
      out.write("\t            \t\tvar tdcityText = par.children(\"td:nth-child(9)\");\r\n");
      out.write("\t            \t\tvar pincodeText = par.children(\"td:nth-child(10)\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\tvar tdphoneText = par.children(\"td:nth-child(11)\");\r\n");
      out.write("\t            \t\tvar tdemgphoneText = par.children(\"td:nth-child(12)\");\r\n");
      out.write("\t            \t\tvar tdemailText = par.children(\"td:nth-child(13)\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\tvar tdButtons = par.children(\"td:nth-child(14)\"); \r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\ttdfistnameText.html(\"<input type='text' id='txtFName' value='\"+tdfistnameText.html()+\"'/>\");\r\n");
      out.write("\t            \t\ttdmiddlenameText.html(\"<input type='text' id='txtMName' value='\"+tdmiddlenameText.html()+\"'/>\");\r\n");
      out.write("\t            \t\ttdlastnameText.html(\"<input type='text' id='txtLName' value='\"+tdlastnameText.html()+\"'/>\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\ttddobText.html(\"<input type='text' id='txtdob' value='\"+tddobText.html()+\"'/>\");\r\n");
      out.write("\t            \t\ttdageText.html(\"<input type='text' id='txtage' value='\"+tdageText.html()+\"'/>\");\r\n");
      out.write("\t            \t\ttdgenderText.html(\"<input type='text' id='txtgender' value='\"+tdgenderText.html()+\"'/>\");\r\n");
      out.write("\r\n");
      out.write("\t            \t\ttdaddressText.html(\"<input type='text' id='txtaddress' value='\"+tdaddressText.html()+\"'/>\");\r\n");
      out.write("\t            \t\ttdstateText.html(\"<input type='text' id='txtstate' value='\"+tdstateText.html()+\"'/>\");\r\n");
      out.write("\t            \t\ttdcityText.html(\"<input type='text' id='txtcity' value='\"+tdcityText.html()+\"'/>\");\r\n");
      out.write("\t            \t\tpincodeText.html(\"<input type='text' id='txtpincode' value='\"+pincodeText.html()+\"'/>\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\ttdphoneText.html(\"<input type='text' id='txtphone' value='\"+tdphoneText.html()+\"'/>\");\r\n");
      out.write("\t            \t\ttdemgphoneText.html(\"<input type='text' id='txtemgphone' value='\"+tdemgphoneText.html()+\"'/>\");\r\n");
      out.write("\t            \t\ttdemailText.html(\"<input type='text' id='txtemail' value='\"+tdemailText.html()+\"'/>\");\r\n");
      out.write("\t            \t\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\ttdButtons.html(\"<img src='css/images/save.png' class='btnSave'/>\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\t$(\".btnSave\").bind(\"click\",onSave);\r\n");
      out.write("\t            \t\t\t            \t\t\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t\t        \t}\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \tfunction onSave(){\r\n");
      out.write("\t\t        \t\talert(\"Save me\");\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t        \t\t\tvar par = $(this).parent().parent();\r\n");
      out.write("            \t\t\t\r\n");
      out.write("\t            \t\tvar tdfistnameText= par.children(\"td:nth-child(1)\"); \r\n");
      out.write("\t            \t\tvar tdmiddlenameText = par.children(\"td:nth-child(2)\"); \r\n");
      out.write("\t            \t\tvar tdlastnameText = par.children(\"td:nth-child(3)\"); \r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\tvar tddobText = par.children(\"td:nth-child(4)\");\r\n");
      out.write("\t            \t\tvar tdageText = par.children(\"td:nth-child(5)\");\r\n");
      out.write("\t            \t\tvar tdgenderText = par.children(\"td:nth-child(6)\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\tvar tdaddressText = par.children(\"td:nth-child(7)\");\r\n");
      out.write("\t            \t\tvar tdstateText = par.children(\"td:nth-child(8)\");\r\n");
      out.write("\t            \t\tvar tdcityText = par.children(\"td:nth-child(9)\");\r\n");
      out.write("\t            \t\tvar pincodeText = par.children(\"td:nth-child(10)\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\tvar tdphoneText = par.children(\"td:nth-child(11)\");\r\n");
      out.write("\t            \t\tvar tdemgphoneText = par.children(\"td:nth-child(12)\");\r\n");
      out.write("\t            \t\tvar tdemailText = par.children(\"td:nth-child(13)\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\tvar tdButtons = par.children(\"td:nth-child(14)\"); \r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\ttdName.html(tdName.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\ttdfistnameText.html(tdfistnameText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\ttdmiddlenameText.html(tdmiddlenameText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\ttdlastnameText.html(tdlastnameText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\ttddobText.html(tddobText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\ttdageText.html(tdageText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\ttdgenderText.html(tdgenderText.children(\"input[type=text]\").val());\r\n");
      out.write("\r\n");
      out.write("\t            \t\ttdaddressText.html(tdaddressText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\ttdstateText.html(tdstateText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\ttdcityText.html(tdcityText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\tpincodeText.html(pincodeText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\ttdphoneText.html(tdphoneText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\ttdemgphoneText.html(tdemgphoneText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\ttdemailText.html(tdemailText.children(\"input[type=text]\").val());\r\n");
      out.write("\t            \t\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\ttdButtons.html(\"<img src='css/images/edit.png' class='btnEdit'/><img src='css/images/delete.png' class='btnDelete'/>\");\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t    \t            $(\".btnEdit\").bind(\"click\",onEdit);\r\n");
      out.write("\t\t\t        \t$(\".btnDelete\").bind(\"click\",onDelete);\r\n");
      out.write("\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t            \t\t\r\n");
      out.write("\t\t        \t}\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \tfunction onDelete(){\r\n");
      out.write("\t\t        \t\t//alert(\"Delete me\");\r\n");
      out.write("\t\t        \t\tvar par = $(this).parent().parent(); //tr\r\n");
      out.write("\t\t        \t\tpar.remove();\r\n");
      out.write("\t\t        \t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#createTeamBtn\").click(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar TableData;\r\n");
      out.write("\t\tTableData = storeTblValues();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//TableData = $.toJSON(TableData);\r\n");
      out.write("\t\tTableData = JSON.stringify(TableData);\r\n");
      out.write("\t\talert(TableData);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t    type: \"POST\",\r\n");
      out.write("\t\t    url:\"/SportManagmentSystem/TeamEntryServlet\",\r\n");
      out.write("\t\t    // data :\"dataSend=age&&category=\"+$(this).val(),   \r\n");
      out.write("\t\t    data: \"dataSend=createTeamBtn&&TableData=\" + TableData,\r\n");
      out.write("\t\t   \t//data:{json :TableData}, \r\n");
      out.write("\t\t   success: function(msg){\r\n");
      out.write("\t\t        // return value stored in msg variable\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction storeTblValues()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t    var TableData = new Array();\r\n");
      out.write("\r\n");
      out.write("\t\t    $('#partitable tr').each(function(row, tr){\r\n");
      out.write("\t\t        TableData[row]={\r\n");
      out.write("\t\t            \"firstname\" : $(tr).find('td:eq(0)').text()\r\n");
      out.write("\t\t            , \"middlename\" :$(tr).find('td:eq(1)').text()\r\n");
      out.write("\t\t            , \"lastname\" : $(tr).find('td:eq(2)').text()\r\n");
      out.write("\t\t            , \"dob\" : $(tr).find('td:eq(3)').text()\r\n");
      out.write("\t\t        } ;   \r\n");
      out.write("\t\t    }); \r\n");
      out.write("\t\t    TableData.shift();  // first row will be empty - so remove\r\n");
      out.write("\t\t    return TableData;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#dobText\").change(function(){\r\n");
      out.write("\t\tif($(this).val()!=undefined ||$(this).val()!=null){\r\n");
      out.write("\t\tvar start = $('#dobText').val();\r\n");
      out.write("     \t\r\n");
      out.write("\t \tvar date = new Date(start);\r\n");
      out.write("     \tvar d = date.getDate();\r\n");
      out.write("\t \tvar m = date.getMonth();\r\n");
      out.write("     \tvar y = date.getFullYear();\r\n");
      out.write("\t \t\r\n");
      out.write("     \tvar now = new Date();\r\n");
      out.write("\t \t\r\n");
      out.write("\t\tvar age = now.getFullYear() - y;\r\n");
      out.write("\t\tvar mdif = now.getMonth() - m + 1; //0=jan\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(mdif < 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t--age;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(mdif == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar ddif = now.getDate() - d;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(ddif < 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t--age;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t \t\r\n");
      out.write("\t \t$('#ageText').val(age);\r\n");
      out.write("     }\r\n");
      out.write("\t \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".dateTimePicker1\").datepicker({\r\n");
      out.write("\t    showOn: \"button\",\r\n");
      out.write("\t    buttonImage: \"css/images/calendar.png\",\r\n");
      out.write("\t    buttonImageOnly: true,\r\n");
      out.write("\t    buttonText: \"\",\r\n");
      out.write("\t    dateFormat:\"dd-M-yy\", \r\n");
      out.write("\t    changeMonth : true,\r\n");
      out.write("           changeYear : true,\r\n");
      out.write("           yearRange: '-100y:c+nn',\r\n");
      out.write("           maxDate: '-1d'\r\n");
      out.write("\t  });\r\n");
      out.write("\tvar picker = new MaterialDatetimePicker({})\r\n");
      out.write("\t.on('submit', function(d) {\r\n");
      out.write("\t  output.innerText = d;\r\n");
      out.write("\t});\r\n");
      out.write("\t    */\t\r\n");
      out.write("\t   $('#p2').hide();\r\n");
      out.write("\t    $('.data').hide();\r\n");
      out.write("\t    $('.searching').off('click').on('click',function(){\r\n");
      out.write("\t    \t$('#p2').show();\r\n");
      out.write("\t    \t//setTimeout(function(){},5000);\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tif(document.getElementById('category').selectedIndex == '0' || document.getElementById('age').selectedIndex == '0' || document.getElementById('gender').selectedIndex == '0'){\r\n");
      out.write("\t    \t\talert(\"Please select Category,Gender and Age.\");\r\n");
      out.write("\t    \t}else{\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t       type: \"post\",\r\n");
      out.write("\t\t\t       url:\"/SportManagmentSystem/TeamEntryServlet\",\r\n");
      out.write("\t\t\t       data:\"dataSend=searchBtn&&category=\"+$(\"#category\").val()+\"&&age=\"+$(\"#age\").val()+\"&&gender=\"+$(\"#gender\").val(),      \r\n");
      out.write("\t\t\t       success:function(data, textStatus, jqXHR)\r\n");
      out.write("\t\t\t\t      {\r\n");
      out.write("\t\t\t    \t\tvar e=jQuery.parseJSON(data);\r\n");
      out.write("\t\t\t\t\t    var options = '';\r\n");
      out.write("\t\t\t\t     \toptions += '<option value=\"NotSelected\"></option>';\r\n");
      out.write("\t\t\t\t\t\tif(e!=undefined && e!=null && e!=\"\" ){\r\n");
      out.write("\t\t\t\t\t\t\t$.each(e, function(key, value){\r\n");
      out.write("\t\t\t\t\t\t\t\toptions += '<option value=\"' + key + '\">' + value + '</option>';\r\n");
      out.write("\t\t\t\t\t\t\t});\t\t     \t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t     $(\"#captainlist\").html(options);\r\n");
      out.write("\t\t\t\t     $('#p2').fadeOut('slow',function(){\r\n");
      out.write("\t\t\t    \t\t\t$('.data').fadeIn('slow');\t\r\n");
      out.write("\t\t\t\t     });\r\n");
      out.write("\t\t\t\t      },\t\t      \r\n");
      out.write("\t\t\t\t      error:function(xhr,status){\r\n");
      out.write("\t\t\t\t\t        console.log(status);\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t    \treturn false;\r\n");
      out.write("\t    });\r\n");
      out.write("\t    var day;\r\n");
      out.write("\t    var month;\r\n");
      out.write("\t    var year;\r\n");
      out.write("\t    $(\"#day\").change(function(){\r\n");
      out.write("\t    \tday=$(this).val();\r\n");
      out.write("\t    \tcalAge();\r\n");
      out.write("\t    });\r\n");
      out.write("\t    $(\"#month\").change(function(){\r\n");
      out.write("\t    \tmonth=$(this).val();\r\n");
      out.write("\t    \tcalAge();\r\n");
      out.write("\t    });\r\n");
      out.write("\t    $(\"#year\").change(function(){\r\n");
      out.write("\t    \tyear=$(this).val();\r\n");
      out.write("\t    \tcalAge();\r\n");
      out.write("\t    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t    calAge =function(e){\r\n");
      out.write("\t    \t\tlet d=31;\r\n");
      out.write("\t    \t\t var valideDate=false;\r\n");
      out.write("\t    \t\tif(!isNaN(day) && !isNaN(month)&&!isNaN(year)){\r\n");
      out.write("\t    \t\t\tif(month=='February'){\r\n");
      out.write("\t    \t\t\t if((this.isLeapyear() && day<30)||day<29){\r\n");
      out.write("\t    \t\t\t\t d=28;\r\n");
      out.write("\t    \t\t\t\t if(this.isLeapyear()){\r\n");
      out.write("\t    \t\t\t\t\td=28;\t \r\n");
      out.write("\t    \t\t\t\t }\r\n");
      out.write("\t    \t\t\t\t valideDate=true;\r\n");
      out.write("\t    \t\t\t }\r\n");
      out.write("\t    \t\t\t}else if(month=='April' || month=='June' ||month=='September' || month=='November' ){\r\n");
      out.write("\t    \t\t\t\tif(day<31){\r\n");
      out.write("\t    \t\t\t\t valideDate=true;\r\n");
      out.write("\t    \t\t\t\t d=31;\t \r\n");
      out.write("\t    \t\t\t }\r\n");
      out.write("\t    \t\t\t}else{\r\n");
      out.write("\t    \t\t\t\tvalideDate=true;\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t\tif(valideDate){\r\n");
      out.write("\t    \t\t\t\tconsole.log(month+'/'+ day+'/'+year);\r\n");
      out.write("\t    \t\t\t\tthis.dob=new Date(month+'/'+ day+'/'+year);\r\n");
      out.write("\t    \t\t\t\tconsole.log(this.dob);\r\n");
      out.write("\t    \t\t\t\tlet ageDifMs = new Date('3/15/2017') - new Date(month+'/'+ day+'/'+year).getTime();\r\n");
      out.write("\t    \t\t\t\tlet ageDate = new Date(ageDifMs);\r\n");
      out.write("\t    \t\t\t\tdayofbirth=d-ageDate.getDate();\r\n");
      out.write("\t    \t\t\t\tmonths=12-(ageDate.getMonth()+1);\r\n");
      out.write("\t    \t\t\t\tvar yrs=Math.abs(ageDate.getUTCFullYear() - 1970);\r\n");
      out.write("\t    \t\t\t\t$('#ageText').text(yrs);\r\n");
      out.write("\t    \t\t\t\tvalideDate=false;\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t\t\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    for(var i=1;i<32;i++){$('#day').append('<option value=\"'+i+'\">'+i+'</option>')}\r\n");
      out.write("\t    for(var i=1;i<13;i++){$('#month').append('<option value=\"'+i+'\">'+i+'</option>')}\r\n");
      out.write("\t    for(var i=1970;i<2017;i++){$('#year').append('<option value=\"'+i+'\">'+i+'</option>')}\r\n");
      out.write("\t    $('.saveTeam').off('submit').on('click',function(){\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tif(document.getElementById(\"captainlist\").selectedIndex == '0' || document.getElementById('teamName').value.length == '0' || document.getElementById('schoolName').value.length == '0' || memberlist.length == '0'){\r\n");
      out.write("\t    \t\talert(\"something wrong\");\r\n");
      out.write("\t    \t\tif(memberlist.length == '0'){\r\n");
      out.write("\t    \t\t\talert(\"Please add team members.\");\r\n");
      out.write("\t    \t\t\tdocument.getElementById('addmemberspan').focus();\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\tif(document.getElementById(\"teamName\").value.length == '0' || document.getElementById(\"schoolName\").value.length == '0'){\r\n");
      out.write("\t    \t\t\talert(\"Please add Team Name and School Name.\")\r\n");
      out.write("\t\t    \t\tdocument.getElementById('show-dialog').focus();\t\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\tif(document.getElementById(\"captainlist\").selectedIndex == '0'){\r\n");
      out.write("\t    \t\t\talert(\"Please select captain name.\")\r\n");
      out.write("\t\t    \t\tdocument.getElementById('captainlist').focus();\t\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\treturn false;\r\n");
      out.write("\t    \t}else{\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\t$.ajax({\r\n");
      out.write("\t\t\t\t    type: \"POST\",\r\n");
      out.write("\t\t\t\t    url:\"/SportManagmentSystem/TeamEntryServlet\",\r\n");
      out.write("\t\t\t\t    //data: \"dataSend=createTeamBtn&&TableData=\" + TableData + \"&&TeamName=\" + $(\"#teamnameText\").val() + \"&&TeamSchoolName=\" + $(\"#teamschoolnameText\").val(),\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t\t   data: {dataSend:'createTeamBtn',TableData: JSON.stringify(memberlist),TeamName: $(\"#teamName\").val(),TeamSchoolName:$(\"#schoolName\").val(),CaptainId:$('#captainlist').val()} ,\r\n");
      out.write("\t\t\t\t    success: function(msg){\r\n");
      out.write("\t\t\t\t        // return value stored in msg variable\r\n");
      out.write("\t\t\t\t    }\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \treturn true;\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<form>\r\n");
      out.write("    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("        <select class=\"mdl-textfield__input\" id=\"category\">\r\n");
      out.write("            <option value=\"\"></option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <label class=\"mdl-textfield__label\" for=\"category\"></label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("        <select class=\"mdl-textfield__input\" id=\"age\">\r\n");
      out.write("            <option value=\"\"></option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <label class=\"mdl-textfield__label\" for=\"age\">Select Age</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("        <select class=\"mdl-textfield__input\" id=\"gender\">\r\n");
      out.write("            <option value=\"\"></option>\r\n");
      out.write("            <option value=\"B\">B</option>\r\n");
      out.write("            <option value=\"G\">G</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <label class=\"mdl-textfield__label\" for=\"gender\">Gender</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button class=\"mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-js-ripple-effect  \r\n");
      out.write("    mdl-button--accent searching\" id=\"tt1\">\r\n");
      out.write("        <i class=\"material-icons\">search</i>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"mdl-tooltip\" data-mdl-for=\"tt1\">\r\n");
      out.write("        Search Captian\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"clear-fix\"></div>\r\n");
      out.write("    <div id=\"p2\" class=\"mdl-progress mdl-js-progress mdl-progress__indeterminate\"></div>\r\n");
      out.write("    <div class=\"clear-fix\"></div>\r\n");
      out.write("    <div class=\"data\">\r\n");
      out.write("    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("        <select class=\"mdl-textfield__input\" id=\"captainlist\">\r\n");
      out.write("            <option value=\"\"></option>\r\n");
      out.write("        </select>\t\r\n");
      out.write("        <label class=\"mdl-textfield__label\" for=\"captainlist\">Select Captain</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button id=\"show-dialog\" type=\"button\" class=\"mdl-button\">Add Team/School Name</button>\r\n");
      out.write("    <div class=\"clear-fix\"></div>\r\n");
      out.write("    <div class=\"inputteamname\" id=\"tt2\"></div>\r\n");
      out.write("    <div class=\"mdl-tooltip\" data-mdl-for=\"tt2\">\r\n");
      out.write("        Team Name\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"clear-fix\"></div>\r\n");
      out.write("    <dialog class=\"mdl-dialog\" id=\"teamnameDialog\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mdl-dialog__content\">\r\n");
      out.write("            <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                <input class=\"mdl-textfield__input\" type=\"text\" id=\"teamName\" maxlength=\"99\">\r\n");
      out.write("                <label class=\"mdl-textfield__label\" for=\"teamName\">Team Name</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                <input class=\"mdl-textfield__input\" type=\"text\" id=\"schoolName\" maxlength=\"99\">\r\n");
      out.write("                <label class=\"mdl-textfield__label\" for=\"schoolName\">School Name</label>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mdl-dialog__actions\">\r\n");
      out.write("            <button type=\"button\" class=\"mdl-button ok\">Ok</button>\r\n");
      out.write("            <button type=\"button\" class=\"mdl-button close\">Cancel</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </dialog>\r\n");
      out.write("    <div class=\"memberlist\">\r\n");
      out.write("     <div class=\"mdl-grid tableHeader\">\r\n");
      out.write("    <div class=\"mdl-cell mdl-cell--3-col\">\r\n");
      out.write("    <span id= \"addmemberspan\" class=\"mdl-chip mdl-chip--contact addmember\">\r\n");
      out.write("   \t<img class=\"mdl-chip__contact\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/add-user.png\"></img>\r\n");
      out.write("\t <span class=\"mdl-chip__text\">Add Member</span>\r\n");
      out.write("    </span>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"mdl-cell mdl-cell--2-col\">\r\n");
      out.write("\t    Action\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"mdl-cell mdl-cell--3-col\">\r\n");
      out.write("\t    Name\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"mdl-cell mdl-cell--2-col\">\r\n");
      out.write("\t    Age\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"mdl-cell mdl-cell--2-col\">\r\n");
      out.write("\t    \r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  <button class=\"mdl-button mdl-js-button mdl-button--raised mdl-button--accent saveTeam\">\r\n");
      out.write(" Save Team\r\n");
      out.write("</button>\r\n");
      out.write("    <dialog class=\"mdl-dialog\" id=\"newmemeber\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mdl-dialog__content\">\r\n");
      out.write("            <div class=\"mdl-grid\">\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--4-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <input class=\"mdl-textfield__input\" type=\"text\" id=\"fistnameText\" maxlength=\"49\">\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"fistnameText\">Name</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--4-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <input class=\"mdl-textfield__input\" type=\"text\" id=\"middlenameText\" maxlength=\"49\">\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"middlenameText\">Father Name</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--4-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <input class=\"mdl-textfield__input\" type=\"text\" id=\"lastnameText\" maxlength=\"49\">\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"lastnameText\">Surname</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<label class=\"mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect\" for=\"checkbox-2\">\r\n");
      out.write("  \t\t\t\t<input type=\"checkbox\" id=\"checkbox-2\" class=\"mdl-checkbox__input\">\r\n");
      out.write("  \t\t\t\t<span class=\"mdl-checkbox__label\">Same as Captain</span>\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("        \t<div class=\"mdl-grid\">\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--12-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <textarea class=\"mdl-textfield__input\"  rows= \"3\" id=\"addressText\" maxlength=\"249\"></textarea>\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"addressText\">Address</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"mdl-grid\">\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--4-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <input class=\"mdl-textfield__input\" type=\"text\" id=\"stateText\" maxlength=\"2\">\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"stateText\">State</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--4-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <input class=\"mdl-textfield__input\" type=\"text\" id=\"cityText\" maxlength=\"19\">\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"cityText\">City</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--4-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <input class=\"mdl-textfield__input\" type=\"text\" id=\"pincodeText\" maxlength=\"6\">\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"pincodeText\">Pin Code</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"mdl-grid dobvals\" >\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--6-col\">\r\n");
      out.write("                   <label>Date of Birth</label>\r\n");
      out.write("                   <select id=\"day\"><option value=\"0\">DD<option></select>\r\n");
      out.write("                   <select id=\"month\"><option value=\"0\">MM<option></select>\r\n");
      out.write("                   <select id=\"year\"><option value=\"0\">YYYY<option></select>               \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--6-col\">\r\n");
      out.write("                        Age:\r\n");
      out.write("                        <span id=\"ageText\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("\t        <select class=\"mdl-textfield__input\" id=\"genderParti\">\r\n");
      out.write("\t            <option value=\"\"></option>\r\n");
      out.write("\t            <option value=\"B\">B</option>\r\n");
      out.write("\t            <option value=\"G\">G</option>\r\n");
      out.write("\t        </select>\r\n");
      out.write("\t        <label class=\"mdl-textfield__label\" for=\"gender\">Gender</label>\r\n");
      out.write("\t   \t\t </div>\r\n");
      out.write("        \t<div class=\"mdl-grid\">\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--4-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <input class=\"mdl-textfield__input\" type=\"text\" id=\"phoneText\" maxlength=\"10\">\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"phoneText\">Phone</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--4-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <input class=\"mdl-textfield__input\" type=\"text\" id=\"emergencyphone\" maxlength=\"10\">\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"emergencyphone\">Emergency Phone</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mdl-cell mdl-cell--4-col\">\r\n");
      out.write("                    <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\r\n");
      out.write("                        <input class=\"mdl-textfield__input\" type=\"text\" id=\"emailText\" maxlength=\"39\">\r\n");
      out.write("                        <label class=\"mdl-textfield__label\" for=\"emailText\">Email</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mdl-dialog__actions\">\r\n");
      out.write("            <button type=\"button\" class=\"mdl-button ok\">Add</button>\r\n");
      out.write("            <button type=\"button\" class=\"mdl-button close\">Cancel</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </dialog>\r\n");
      out.write("   </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- form>\r\n");
      out.write("<div class=container></div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"labels_category\"><span>Please select category:</span></div><select id=\"category\"></select>\r\n");
      out.write("\t<div class=\"labels_age\"><span>Please select age:</span></div><select id=\"age\"></select>\r\n");
      out.write("\t<div class=\"labels_gender\"><span>Please select gender:</span></div><select id=\"gender\">\r\n");
      out.write("\t<option value=\"select\">Select a gender</option> \r\n");
      out.write("\t<option  value=\"B\">B</option> \r\n");
      out.write("\t<option value=\"G\">G</option> \r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"buttondiv\">\r\n");
      out.write("\t\t<input type=\"button\" name=\"searchBtn\" id=\"searchBtn\" value=\"Search Captain\">\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("<select id=\"captainlist\"></select>\t\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"buttondiv\">\r\n");
      out.write("\t\t<input type=\"button\" name=\"addBtn\" id=\"addBtn\" value=\"Add Record\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"labels_category\">\r\n");
      out.write("<span>First Name:</span></div>\r\n");
      out.write("<input type=\"text\" class=\"firstname\"  id=\"fistnameText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Last Name:</span></div><input type=\"text\" class=\"lastname\"  id=\"lastnameText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Middle Name:</span></div><input type=\"text\" class=\"middlename\"  id=\"middlenameText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Date of Birth:</span></div>\r\n");
      out.write("<input type=\"text\" class ='dateTimePicker1' id=\"dobText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Age:</span></div><input type=\"text\" class=\"age\"  id=\"ageText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Gender:</span></div><input type=\"text\" class=\"gender\"  id=\"genderText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Address:</span></div><input type=\"text\" class=\"addressline\"  id=\"addressText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>State:</span></div><input type=\"text\" class=\"state\"  id=\"stateText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>City:</span></div><input type=\"text\" class=\"city\"  id=\"cityText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Pincode:</span></div><input type=\"text\" class=\"pincode\"  id=\"pincodeText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Phone:</span></div><input type=\"text\" class=\"phone\"  id=\"phoneText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Emergency Phone:</span></div><input type=\"text\" class=\"emergencyphone\"  id=\"emergencyPhoneText\" value=\"sampada\">\r\n");
      out.write("<div class=\"labels_category\"><span>Email:</span></div><input type=\"text\" class=\"email\"  id=\"emailText\" value=\"sampada\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"tablediv\">\r\n");
      out.write("<table cellspacing=\"10px\" id=\"partitable\" class=\"table\"> \r\n");
      out.write("    <tr class=\"tr\"> \r\n");
      out.write("    \t<th class=\"th\" scope=\"col\">First Name</th>\r\n");
      out.write("        <th class=\"th\" scope=\"col\">Middle Name</th> \r\n");
      out.write("        <th class=\"th\" scope=\"col\">Last Name</th> \r\n");
      out.write("        <th class=\"th\" scope=\"col\">Date Of Birth</th> \r\n");
      out.write("        <th class=\"th\" scope=\"col\">Age</th> \r\n");
      out.write("        <th class=\"th\" scope=\"col\">Gender</th> \r\n");
      out.write("        <th class=\"th\" scope=\"col\">Address</th>  \r\n");
      out.write("        <th class=\"th\" scope=\"col\">State</th>  \r\n");
      out.write("        <th class=\"th\" scope=\"col\">City</th>  \r\n");
      out.write("        <th class=\"th\" scope=\"col\">Pincode</th>  \r\n");
      out.write("        <th class=\"th\" scope=\"col\">Phone</th>\r\n");
      out.write("        <th class=\"th\" scope=\"col\">Emergency Phone</th>\r\n");
      out.write("        <th class=\"th\" scope=\"col\">Email</th>       \r\n");
      out.write("        <th class=\"th\" scope=\"col\">Action</th>          \r\n");
      out.write("    </tr> \r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"buttondiv\">\r\n");
      out.write("\t\t<input type=\"button\" name=\"createTeamBtn\" id=\"createTeamBtn\" value=\"Create Team\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>  ");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
